n_itr: 1

agent: ddpm
dataset: anime-faces

seed: 0
num_samples: 25

no_gpu: False
which_gpu: 0
image_log_freq: 10000
tabular_log_freq: 1000
param_log_freq: 10000

data_config:
    dataset_path: ???
    image_size: 48
    batch_size: 100
    augment_horizontal_flip: True

logger_config:
    exp_prefix: ${agent}_${dataset}
    seed: ${seed}
    snapshot_mode: last

policy_config:
    image_size: ${data_config.image_size}
    objective: pred_x0
    noise_timesteps: 1000
    loss_type: huber
    beta_schedule: cosine
    sampling_timesteps: 1000
    lr: 1e-4

# disable hypra log
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
